# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reclaim < Formula
  desc "A deliberately boring macOS disk cleaner, app uninstaller, and app updater."
  homepage "https://github.com/ihdev524/reclaim"
  version "1.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/ihdev524/reclaim/releases/download/v1.0.1/reclaim_1.0.1_darwin_amd64.tar.gz"
    sha256 "f7a39cf6c490dd23cab00fde0b356e2cd16fff37007d63d7823e3623907319a6"

    define_method(:install) do
      bin.install "reclaim"
      bash_completion.install "completions/reclaim.bash" => "reclaim"
      zsh_completion.install "completions/_reclaim"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/ihdev524/reclaim/releases/download/v1.0.1/reclaim_1.0.1_darwin_arm64.tar.gz"
    sha256 "4b261505f93ad79602331f72686f75206d8aa941f6e93ea5fcf23b4e79d1766b"

    define_method(:install) do
      bin.install "reclaim"
      bash_completion.install "completions/reclaim.bash" => "reclaim"
      zsh_completion.install "completions/_reclaim"
    end
  end

  test do
    system "#{bin}/reclaim", "version"
  end
end
