# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reclaim < Formula
  desc "A deliberately boring macOS disk cleaner, app uninstaller, and app updater."
  homepage "https://github.com/ihdev524/reclaim"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/ihdev524/reclaim/releases/download/v1.0.0/reclaim_1.0.0_darwin_amd64.tar.gz"
    sha256 "a1be699b4de5ec37c2d8782f9eea6f99452d92f9bdf0556dec71abb4a3c557eb"

    define_method(:install) do
      bin.install "reclaim"
      bash_completion.install "completions/reclaim.bash" => "reclaim"
      zsh_completion.install "completions/_reclaim"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/ihdev524/reclaim/releases/download/v1.0.0/reclaim_1.0.0_darwin_arm64.tar.gz"
    sha256 "e6981169f5f2efe2bcfa95c489c4a37edf9fabfcb606e293b3b3af138394f42a"

    define_method(:install) do
      bin.install "reclaim"
      bash_completion.install "completions/reclaim.bash" => "reclaim"
      zsh_completion.install "completions/_reclaim"
    end
  end

  test do
    system "#{bin}/reclaim", "version"
  end
end
